name: guided_diff
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py38h06a4308_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpi=1.0=mpich
  - mpi4py=3.1.4=py38hfc96bbd_0
  - mpich=3.3.2=external_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.24.3=py38h14f4228_0
  - numpy-base=1.24.3=py38h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - pillow=9.4.0=py38h6a678d5_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - urllib3=1.26.15=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==1.4.0
    - accelerate==0.21.0
    - addict==2.4.0
    - aiofiles==24.1.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - albumentations==1.3.0
    - altair==5.4.1
    - antlr4-python3-runtime==4.9.3
    - anyio==4.4.0
    - argcomplete==3.5.0
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==23.1.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.12.3
    - bitsandbytes==0.41.0
    - blobfile==2.0.2
    - boto==2.49.0
    - boto3==1.35.3
    - botocore==1.35.3
    - brotli==1.1.0
    - cachetools==5.3.0
    - click==8.1.8
    - cmake==3.31.2
    - compressai==1.2.4
    - contourpy==1.0.7
    - crcmod==1.7
    - cvdata==0.0.3
    - cycler==0.11.0
    - dacite==1.7.0
    - deepspeed==0.9.5
    - deprecated==1.2.14
    - diffusers==0.16.1
    - dill==0.3.8
    - dnspython==2.6.1
    - docker-pycreds==0.4.0
    - einops==0.6.1
    - einops-exts==0.0.4
    - exceptiongroup==1.2.2
    - fastapi==0.115.6
    - fasteners==0.19
    - ffmpy==0.5.0
    - fiftyone==0.25.0
    - fiftyone-brain==0.17.0
    - fiftyone-db==1.1.5
    - filelock==3.12.0
    - flatbuffers==23.5.26
    - fonttools==4.39.4
    - frozenlist==1.3.3
    - fsspec==2023.5.0
    - ftfy==6.1.3
    - future==0.18.3
    - gast==0.4.0
    - gcs-oauth2-boto-plugin==3.2
    - gitdb==4.0.12
    - gitpython==3.1.44
    - glob2==0.7
    - google-apitools==0.5.32
    - google-auth==2.17.0
    - google-auth-httplib2==0.2.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - google-reauth==0.1.1
    - gradio==3.35.2
    - gradio-client==0.2.9
    - graphql-core==3.2.3
    - grpcio==1.54.2
    - gsutil==5.30
    - h11==0.14.0
    - h2==4.1.0
    - h5py==3.10.0
    - hjson==3.1.0
    - hpack==4.0.0
    - httpcore==0.17.3
    - httplib2==0.20.4
    - httpx==0.24.0
    - huggingface-hub==0.19.4
    - humanize==4.10.0
    - hypercorn==0.17.3
    - hyperframe==6.0.1
    - imageio==2.28.1
    - imgaug==0.4.0
    - imhist==0.0.4
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - imwatermark==0.0.2
    - inflate64==1.0.0
    - invisible-watermark==0.2.0
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - jsonlines==4.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - kaleido==0.2.1
    - keras==2.13.1
    - kiwisolver==1.4.4
    - kornia==0.7.0
    - lazy-loader==0.2
    - libclang==16.0.6
    - linkify-it-py==2.0.3
    - lit==18.1.8
    - llava==1.1.1
    - lmdb==1.4.1
    - lxml==4.9.3
    - markdown==3.4.3
    - markdown-it-py==2.2.0
    - markdown2==2.5.1
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mongoengine==0.24.2
    - monotonic==1.6
    - motor==3.5.1
    - mpmath==1.3.0
    - multidict==6.0.4
    - multivolumefile==0.2.3
    - narwhals==1.21.1
    - networkx==3.1
    - ninja==1.11.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - oauth2client==4.1.3
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - openai-clip==1.0.1
    - opencv-python==4.7.0.68
    - opencv-python-headless==4.7.0.72
    - openimages==0.0.1
    - opt-einsum==3.3.0
    - orjson==3.10.14
    - packaging==23.1
    - pandas==2.0.3
    - peft==0.4.0
    - pip==23.3.2
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.0.0
    - plotly==5.23.0
    - pprintpp==0.4.0
    - priority==2.0.0
    - protobuf==4.23.1
    - psutil==5.9.5
    - py-cpuinfo==9.0.0
    - py7zr==0.22.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pybcj==1.0.2
    - pycryptodomex==3.18.0
    - pydantic==1.10.20
    - pydash==8.0.3
    - pydeprecate==0.3.2
    - pydub==0.25.1
    - pygments==2.19.1
    - pyiqa==0.1.8
    - pymongo==4.8.0
    - pyparsing==3.0.9
    - pyppmd==1.1.0
    - python-dateutil==2.8.2
    - python-multipart==0.0.20
    - pytorch-lightning==1.7.7
    - pytorch-msssim==1.0.0
    - pytorch-ssim==0.1
    - pytz==2023.3.post1
    - pyu2f==0.1.5
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzstd==0.16.1
    - qudida==0.0.4
    - rarfile==4.2
    - referencing==0.35.1
    - regex==2023.5.5
    - requests-oauthlib==1.3.1
    - retry-decorator==1.1.1
    - retrying==1.3.4
    - rpds-py==0.20.1
    - rsa==4.7.2
    - s3transfer==0.10.2
    - safetensors==0.4.1
    - scikit-image==0.20.0
    - scikit-learn==1.2.2
    - scipy==1.9.1
    - semantic-version==2.10.0
    - sentencepiece==0.1.99
    - sentry-sdk==2.19.2
    - setproctitle==1.3.4
    - setuptools==68.2.2
    - shapely==2.0.2
    - shortuuid==1.0.13
    - smmap==5.0.2
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - soupsieve==2.6
    - sse-starlette==0.10.3
    - sseclient-py==1.8.0
    - starlette==0.41.3
    - strawberry-graphql==0.138.1
    - svgwrite==1.4.3
    - sympy==1.12
    - tabulate==0.9.0
    - taming-transformers==0.0.1
    - taskgroup==0.0.0a4
    - tenacity==9.0.0
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.0
    - tensorflow==2.13.1
    - tensorflow-estimator==2.13.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==2.3.0
    - texttable==1.7.0
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - timm==1.0.13
    - tokenizers==0.13.3
    - toml==0.10.2
    - tomli==2.0.1
    - torch==2.0.1
    - torch-fidelity==0.3.0
    - torchmetrics==0.11.4
    - torchvision==0.15.2
    - tqdm==4.65.0
    - transformers==4.31.0
    - triton==2.0.0
    - typing-extensions==4.12.2
    - tzdata==2023.3
    - tzlocal==5.2
    - uc-micro-py==1.0.3
    - universal-analytics-python3==1.1.1
    - uvicorn==0.33.0
    - voluptuous==0.13.1
    - voxel51-eta==0.12.7
    - wandb==0.18.7
    - wavedrom==2.0.3.post3
    - wcwidth==0.2.12
    - websockets==13.1
    - werkzeug==2.3.4
    - wheel==0.41.3
    - wrapt==1.16.0
    - wsproto==1.2.0
    - xmltodict==0.13.0
    - yapf==0.40.2
    - yarl==1.9.2
    - zipp==3.15.0
prefix: /media/EXT0/daole/anaconda3/envs/guided_diff
